name: CI Cache Demo

on:
  push:
    branches: [main]

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-84a7669
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-84a7669

      - name: Echo cache result
        run: echo "Cache step completed"
